### ISSUE TITLE
Test failing during chart generation?

### ISSUE THREAD

**Issue by benstilwell** [tarkal/highchart-lambda-export-server#10]
I'm trying to setup an export server in lambda function but am getting an error thrown when I attempt to test it. I've followed this guide but still get an error when attempting to test a simple chart.

Error:
{
  "errorType": "string",
  "errorMessage": "0x03 error when performing chart generation: please check your input data",
  "trace": []
}
The Lambda does have environment variables just in case:

FONTCONFIG_PATH /var/task/lib

PHANTOMJS_ARCH x64

PHANTOMJS_PLATFORM linux

         START RequestId: 2b619486-5ff0-4f50-a35b-d705d759ac1e Version: $LATEST
         2021-06-09T18:52:26.701Z    2b619486-5ff0-4f50-a35b-d705d759ac1e    INFO    {
           xAxis: { categories: [ 'Jan', 'Feb', 'Mar' ] },
           series: [ { data: [Array] } ]
         }
         2021-06-09T18:52:27.080Z    2b619486-5ff0-4f50-a35b-d705d759ac1e    INFO    Wed Jun 09 2021 18:52:27 GMT+0000 (Coordinated Universal Time) [error] phantom worker 2 error - /var/task/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: error while loading shared libraries: libuuid.so.1: cannot open shared object file: No such file or directory

         2021-06-09T18:52:27.082Z    2b619486-5ff0-4f50-a35b-d705d759ac1e    INFO    Wed Jun 09 2021 18:52:27 GMT+0000 (Coordinated Universal Time) [error] phantom worker 1 error - /var/task/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: error while loading shared libraries: libuuid.so.1: cannot open shared object file: No such file or directory

         2021-06-09T18:52:27.119Z    2b619486-5ff0-4f50-a35b-d705d759ac1e    ERROR   Invoke Error    {"errorType":"Error","errorMessage":"0x03 error when performing chart generation: please check your input data","stack":["Error: 0x03 error when performing chart generation: please check your input data","    at _homogeneousError (/var/runtime/CallbackContext.js:12:12)","    at postError (/var/runtime/CallbackContext.js:29:54)","    at done (/var/runtime/CallbackContext.js:56:7)","    at fail (/var/runtime/CallbackContext.js:68:7)","    at /var/runtime/CallbackContext.js:104:16"]}
         END RequestId: 2b619486-5ff0-4f50-a35b-d705d759ac1e
         REPORT RequestId: 2b619486-5ff0-4f50-a35b-d705d759ac1e  Duration: 435.71 ms

**Comment by aza1978** [comment]
You need to add more libraries - this got me past that error

yumdownloader fontconfig.x86_64 freetype.x86_64 expat.x86_64 libuuid.x86_64 bzip2-libs.x86_64 libpng.x86_64

That said highcharts just times out generating output for me now.
